version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto24
    commands:
      - java -version
  pre_build:
    commands:
      - export AWS_ACCOUNT_ID=$(echo $CODEBUILD_PROJECT_ARN | cut -d ':' -f 5)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - ./gradlew bootBuildImage --no-daemon --imagePlatform $IMAGE_PLATFORM
      - docker images

  post_build:
    commands:
      - docker tag bcguo/spring-boot-demo:latest $IMAGE_REPO:$IMAGE_TAG
      - docker push $IMAGE_REPO:$IMAGE_TAG
      - envsubst < k8s-deployment.yaml > k8s-deployment.yaml

artifacts:
  files:
    - k8s-deployment.yaml
